[workspace]
members = [
    "crates/aura-core",
    "crates/aura-net",
    "crates/aura-discover",
    "crates/aura-ingest",
    "crates/aura-store",
#    "bench",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = { version = "1.0.149" }
toml = { version = "1.1.2+spec-1.1.0" }
chrono = { version = "0.4.44", features = ["serde"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "tls-rustls", "postgres", "chrono"] }
tokio = { version = "1.52.3", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4", "with-serde_json-1"] }
tracing = { version = "0.1.44" }
redis = { version = "1.2.1", features = ["tokio-comp", "streams"] }
bytes = { version = "1.11.1" }
tokio-util = { version ="0.7.18", features = ["codec"] }
arc-swap = { version = "1.9.1" }
thiserror = { version = "2.0.18" }
libc = { version = "1.0.0-alpha.3" }
crossbeam-channel = { version = "0.5.15" }
futures-util = { version = "0.3.32" }
parking_lot = { version = "0.12.5" }

[package]
name = "aura-epics"
version = "0.1.0"
edition = "2024"
description = "Autonomous Universal Rust Archiver for EPICS Control Systems"
license = "MIT"
default-run = "aura"

[[bin]]
name = "aura"
path = "src/main.rs"

[dependencies]
aura-core = { path = "crates/aura-core" }
aura-net = { path = "crates/aura-net" }
aura-ingest = { path = "crates/aura-ingest" }
aura-store = { path = "crates/aura-store" }
aura-discover = { path = "crates/aura-discover" }

serde_json = { workspace = true }
tracing = { workspace = true }
tokio-postgres = { workspace = true }
redis = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing-subscriber = { workspace = true }
tokio-util = { workspace = true }
arc-swap = { workspace = true }
futures-util = { workspace = true }
chrono = { workspace = true }

sys-info = "0.9.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"