-- ═══════════════════════════════════════════════════════════════════════
-- 010_alert_log: System alert history.
-- ═══════════════════════════════════════════════════════════════════════
--
-- Generated by aura-discover when:
--   - A PV is configured but not connected (IOC down or PV not found)
--   - An IOC is detected on the network but not in pv_config
--   - An IOC transitions to Offline state
--   - An ingest shard is lost (instance down)
--   - A PV is served by a different IOC than expected_ioc
--
-- Read by GET /api/v1/alerts. Old alerts auto-cleaned by retention.

CREATE TABLE IF NOT EXISTS alert_log
(
    id              BIGSERIAL,
    time            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    level           TEXT        NOT NULL DEFAULT 'warning',  -- info, warning, critical
    source          TEXT        NOT NULL DEFAULT 'discover', -- discover, ingest, store
    category        TEXT        NOT NULL DEFAULT 'system',   -- system, pv, ioc, shard
    pv_name         TEXT,                                    -- affected PV (if applicable)
    ioc_addr        TEXT,                                    -- affected IOC (if applicable)
    message         TEXT        NOT NULL,
    details         JSONB       NOT NULL DEFAULT '{}',       -- additional context
    acknowledged    BOOLEAN     NOT NULL DEFAULT FALSE,
    acknowledged_by TEXT,
    acknowledged_at TIMESTAMPTZ
);

SELECT create_hypertable('alert_log', 'time',
                         chunk_time_interval => INTERVAL '7 days',
                         if_not_exists => TRUE
       );

-- Recent alerts query (dashboard).
CREATE INDEX IF NOT EXISTS idx_alert_log_time
    ON alert_log (time DESC);

-- Filter by level (critical first).
CREATE INDEX IF NOT EXISTS idx_alert_log_level
    ON alert_log (level, time DESC);

-- Filter by PV name.
CREATE INDEX IF NOT EXISTS idx_alert_log_pv
    ON alert_log (pv_name, time DESC) WHERE pv_name IS NOT NULL;

-- Unacknowledged alerts.
CREATE INDEX IF NOT EXISTS idx_alert_log_unacked
    ON alert_log (time DESC) WHERE acknowledged = FALSE;

-- ─── Compression ───────────────────────────────────────────────────
ALTER TABLE alert_log
    SET (
        timescaledb.compress,
        timescaledb.compress_orderby = 'time DESC'
        );
SELECT add_compression_policy('alert_log', INTERVAL '24 hours',
                              if_not_exists => TRUE);

-- ─── Retention: 1 year of alert history ────────────────────────────
SELECT add_retention_policy('alert_log', INTERVAL '365 days',
                            if_not_exists => TRUE);

COMMENT ON TABLE alert_log IS 'System alert history. Generated by aura-discover, read by API.';