//! Alert log read/write operations.
//!
//! Alerts are generated by `aura-discover` (IOC offline, PV not connected, shard lost) and read by `aura-api`.

use chrono::{DateTime, Utc};
use std::borrow::Cow;
use std::fmt;
use std::str::FromStr;

use sqlx::postgres::PgPool;

use aura_core::AlertLevel;
use aura_core::error::{AuraError, AuraResult};

mod sql {
    pub const INSERT: &str = "INSERT INTO alert_log (level, source, category, pv_name, ioc_guid, message, details) \
         VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id";

    pub const INSERT_UNNEST: &str = "INSERT INTO alert_log (level, source, category, pv_name, ioc_guid, message, details) \
         SELECT * FROM UNNEST(\
           $1::text[], $2::text[], $3::text[], $4::text[], $5::text[], $6::text[], $7::jsonb[]\
         ) RETURNING id";

    pub const RECENT: &str = "SELECT id, time, level, source, category, pv_name, ioc_guid, \
         message, details, acknowledged \
         FROM alert_log ORDER BY time DESC LIMIT $1";

    pub const UNACKED: &str = "SELECT id, time, level, source, category, pv_name, ioc_guid, \
         message, details, acknowledged \
         FROM alert_log WHERE acknowledged = FALSE \
         ORDER BY time DESC LIMIT $1";

    pub const BY_TIME_RANGE: &str = "SELECT id, time, level, source, category, pv_name, ioc_guid, \
         message, details, acknowledged \
         FROM alert_log WHERE time >= $1 AND time < $2 \
         ORDER BY time DESC LIMIT $3";

    pub const BY_LEVEL: &str = "SELECT id, time, level, source, category, pv_name, ioc_guid, \
         message, details, acknowledged \
         FROM alert_log WHERE level = $1 \
         ORDER BY time DESC LIMIT $2";

    pub const BY_CATEGORY: &str = "SELECT id, time, level, source, category, pv_name, ioc_guid, \
         message, details, acknowledged \
         FROM alert_log WHERE category = $1 \
         ORDER BY time DESC LIMIT $2";

    pub const BY_PV: &str = "SELECT id, time, level, source, category, pv_name, ioc_guid, \
         message, details, acknowledged \
         FROM alert_log WHERE pv_name = $1 \
         ORDER BY time DESC LIMIT $2";

    pub const ACKNOWLEDGE: &str = "UPDATE alert_log SET acknowledged = TRUE, acknowledged_by = $1, \
         acknowledged_at = NOW() WHERE id = $2 AND acknowledged = FALSE";

    pub const ACKNOWLEDGE_BATCH: &str = "UPDATE alert_log SET acknowledged = TRUE, acknowledged_by = $1, \
         acknowledged_at = NOW() WHERE id = ANY($2) AND acknowledged = FALSE";

    pub const COUNT_UNACKED: &str = "SELECT COUNT(*) FROM alert_log WHERE acknowledged = FALSE";

    pub const COUNT_BY_LEVEL: &str = "SELECT level, COUNT(*) as cnt FROM alert_log \
         WHERE acknowledged = FALSE GROUP BY level";

    pub const DELETE_OLD: &str = "DELETE FROM alert_log WHERE time < $1";
}

/// Common alert source strings as statics, avoiding heap allocation.
pub mod sources {
    pub const STORE: &str = "store";
    pub const DISCOVER: &str = "discover";
    pub const INGEST: &str = "ingest";
    pub const API: &str = "api";
    pub const SYSTEM: &str = "system";
}

/// Alert category for filtering and routing (Copy, no allocation).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AlertCategory {
    System,
    Pv,
    Ioc,
    Shard,
}

impl AlertCategory {
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::System => "system",
            Self::Pv => "pv",
            Self::Ioc => "ioc",
            Self::Shard => "shard",
        }
    }

    pub const ALL: [Self; 4] = [Self::System, Self::Pv, Self::Ioc, Self::Shard];
}

impl FromStr for AlertCategory {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "system" => Ok(Self::System),
            "pv" => Ok(Self::Pv),
            "ioc" => Ok(Self::Ioc),
            "shard" => Ok(Self::Shard),
            other => Err(format!("unknown alert category: {other:?}")),
        }
    }
}

impl fmt::Display for AlertCategory {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// An alert to be written to the log.
#[derive(Debug, Clone)]
pub struct Alert {
    pub level: AlertLevel,
    pub source: Cow<'static, str>,
    pub category: AlertCategory,
    pub pv_name: Option<Cow<'static, str>>,
    pub ioc_guid: Option<Cow<'static, str>>,
    pub message: String,
    pub details: serde_json::Value,
}

impl Alert {
    /// Create an alert with a static source.
    pub fn new(level: AlertLevel, category: AlertCategory, message: impl Into<String>) -> Self {
        Self {
            level,
            category,
            source: Cow::Borrowed(sources::STORE),
            pv_name: None,
            ioc_guid: None,
            message: message.into(),
            details: serde_json::Value::Object(Default::default()),
        }
    }

    /// Set source from a well-known static string.
    pub fn with_source_static(mut self, source: &'static str) -> Self {
        self.source = Cow::Borrowed(source);
        self
    }

    /// Set source from a dynamic string.
    pub fn with_source(mut self, source: impl Into<String>) -> Self {
        self.source = Cow::Owned(source.into());
        self
    }

    pub fn with_pv(mut self, pv: impl Into<String>) -> Self {
        self.pv_name = Some(Cow::Owned(pv.into()));
        self
    }

    /// Set PV from a static string.
    pub fn with_pv_static(mut self, pv: &'static str) -> Self {
        self.pv_name = Some(Cow::Borrowed(pv));
        self
    }

    pub fn with_ioc(mut self, guid: impl Into<String>) -> Self {
        self.ioc_guid = Some(Cow::Owned(guid.into()));
        self
    }

    pub fn with_details(mut self, details: serde_json::Value) -> Self {
        self.details = details;
        self
    }

    /// Approximate heap memory used.
    pub fn mem_size(&self) -> usize {
        let source_heap = match &self.source {
            Cow::Borrowed(_) => 0,
            Cow::Owned(s) => s.len(),
        };
        let pv_heap = self.pv_name.as_ref().map_or(0, |c| match c {
            Cow::Borrowed(_) => 0,
            Cow::Owned(s) => s.len() + 24,
        });
        let ioc_heap = self.ioc_guid.as_ref().map_or(0, |c| match c {
            Cow::Borrowed(_) => 0,
            Cow::Owned(s) => s.len() + 24,
        });
        64 + source_heap
            + self.message.len()
            + pv_heap
            + ioc_heap
            + crate::writer::json::estimate_json_size(&self.details)
    }
}

impl fmt::Display for Alert {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "[{}] {}: {}", self.level, self.category, self.message)
    }
}

/// A stored alert retrieved from the database, with typed enums.
/// Strings are moved from the internal `AlertRow`.
#[derive(Debug, Clone)]
pub struct StoredAlert {
    pub id: i64,
    pub time: DateTime<Utc>,
    pub level: AlertLevel,
    pub source: String,
    pub category: AlertCategory,
    pub pv_name: Option<String>,
    pub ioc_guid: Option<String>,
    pub message: String,
    pub details: serde_json::Value,
    pub acknowledged: bool,
}

impl StoredAlert {
    pub fn is_critical(&self) -> bool {
        self.level == AlertLevel::Critical
    }

    pub fn age(&self) -> chrono::Duration {
        Utc::now() - self.time
    }
}

impl fmt::Display for StoredAlert {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "[#{} {}] [{}] {}: {}{}",
            self.id,
            self.time.format("%Y-%m-%d %H:%M:%S"),
            self.level,
            self.category,
            self.message,
            if self.acknowledged { " (ack)" } else { "" }
        )
    }
}

/// Unacknowledged alert counts grouped by level.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct AlertSummary {
    pub info: i64,
    pub warning: i64,
    pub critical: i64,
}

impl AlertSummary {
    pub fn total(&self) -> i64 {
        self.info + self.warning + self.critical
    }
    pub fn has_critical(&self) -> bool {
        self.critical > 0
    }
    pub fn is_clear(&self) -> bool {
        self.total() == 0
    }
}

impl fmt::Display for AlertSummary {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{} alerts ({} critical, {} warning, {} info)",
            self.total(),
            self.critical,
            self.warning,
            self.info
        )
    }
}

/// sqlx row — moves into `StoredAlert`.
#[derive(Debug, sqlx::FromRow)]
struct AlertRow {
    id: i64,
    time: DateTime<Utc>,
    level: String,
    source: String,
    category: String,
    pv_name: Option<String>,
    ioc_guid: Option<String>,
    message: String,
    details: serde_json::Value,
    acknowledged: bool,
}

impl AlertRow {
    /// Convert to `StoredAlert`, moving Strings .
    /// Logs a warning if level/category is unrecognized (data corruption).
    fn into_stored(self) -> StoredAlert {
        let level = match AlertLevel::from_str(&self.level) {
            Ok(l) => l,
            Err(e) => {
                tracing::warn!(id = self.id, raw = %self.level, "{e}, defaulting to Warning");
                AlertLevel::Warning
            }
        };
        let category = match AlertCategory::from_str(&self.category) {
            Ok(c) => c,
            Err(e) => {
                tracing::warn!(id = self.id, raw = %self.category, "{e}, defaulting to System");
                AlertCategory::System
            }
        };
        StoredAlert {
            id: self.id,
            time: self.time,
            level,
            source: self.source, // moved
            category,
            pv_name: self.pv_name,   // moved
            ioc_guid: self.ioc_guid, // moved
            message: self.message,   // moved
            details: self.details,   // moved
            acknowledged: self.acknowledged,
        }
    }
}

/// Clamp limit to a safe range.
#[inline]
fn safe_limit(limit: i64) -> i64 {
    limit.max(1).min(10_000)
}

/// Alert log data access object.
pub struct AlertDao;

impl AlertDao {
    /// Write a single alert. Returns the generated ID.
    pub async fn write(pool: &PgPool, alert: &Alert) -> AuraResult<i64> {
        sqlx::query_scalar::<_, i64>(sql::INSERT)
            .bind(alert.level.as_str())
            .bind(alert.source.as_ref())
            .bind(alert.category.as_str())
            .bind(alert.pv_name.as_deref())
            .bind(alert.ioc_guid.as_deref())
            .bind(&alert.message)
            .bind(&alert.details)
            .fetch_one(pool)
            .await
            .map_err(|e| AuraError::database(format!("write alert: {e}")))
    }

    /// Write N alerts in a single SQL round-trip via UNNEST.
    /// Returns the generated IDs.
    pub async fn write_batch(pool: &PgPool, alerts: &[Alert]) -> AuraResult<Vec<i64>> {
        if alerts.is_empty() {
            return Ok(Vec::new());
        }

        let n = alerts.len();
        let mut levels = Vec::with_capacity(n);
        let mut sources_v = Vec::with_capacity(n);
        let mut categories = Vec::with_capacity(n);
        let mut pv_names: Vec<Option<&str>> = Vec::with_capacity(n);
        let mut ioc_guids: Vec<Option<&str>> = Vec::with_capacity(n);
        let mut messages = Vec::with_capacity(n);
        let mut details_v: Vec<&serde_json::Value> = Vec::with_capacity(n);

        for a in alerts {
            levels.push(a.level.as_str());
            sources_v.push(a.source.as_ref());
            categories.push(a.category.as_str());
            pv_names.push(a.pv_name.as_deref());
            ioc_guids.push(a.ioc_guid.as_deref());
            messages.push(a.message.as_str());
            details_v.push(&a.details);
        }

        let ids: Vec<i64> = sqlx::query_scalar(sql::INSERT_UNNEST)
            .bind(&levels)
            .bind(&sources_v)
            .bind(&categories)
            .bind(&pv_names)
            .bind(&ioc_guids)
            .bind(&messages)
            .bind(&details_v)
            .fetch_all(pool)
            .await
            .map_err(|e| AuraError::database(format!("write_batch UNNEST ({n} alerts): {e}")))?;

        Ok(ids)
    }

    /// Get recent alerts (newest first).
    pub async fn get_recent(pool: &PgPool, limit: i64) -> AuraResult<Vec<StoredAlert>> {
        let rows = sqlx::query_as::<_, AlertRow>(sql::RECENT)
            .bind(safe_limit(limit))
            .fetch_all(pool)
            .await
            .map_err(|e| AuraError::database(format!("get_recent: {e}")))?;
        Ok(rows.into_iter().map(AlertRow::into_stored).collect())
    }

    /// Get unacknowledged alerts (newest first).
    pub async fn get_unacked(pool: &PgPool, limit: i64) -> AuraResult<Vec<StoredAlert>> {
        let rows = sqlx::query_as::<_, AlertRow>(sql::UNACKED)
            .bind(safe_limit(limit))
            .fetch_all(pool)
            .await
            .map_err(|e| AuraError::database(format!("get_unacked: {e}")))?;
        Ok(rows.into_iter().map(AlertRow::into_stored).collect())
    }

    /// Get alerts in a time range (uses hypertable time index).
    pub async fn get_by_time_range(
        pool: &PgPool,
        start: DateTime<Utc>,
        end: DateTime<Utc>,
        limit: i64,
    ) -> AuraResult<Vec<StoredAlert>> {
        let rows = sqlx::query_as::<_, AlertRow>(sql::BY_TIME_RANGE)
            .bind(start)
            .bind(end)
            .bind(safe_limit(limit))
            .fetch_all(pool)
            .await
            .map_err(|e| AuraError::database(format!("get_by_time_range: {e}")))?;
        Ok(rows.into_iter().map(AlertRow::into_stored).collect())
    }

    /// Get alerts filtered by level.
    pub async fn get_by_level(
        pool: &PgPool,
        level: AlertLevel,
        limit: i64,
    ) -> AuraResult<Vec<StoredAlert>> {
        let rows = sqlx::query_as::<_, AlertRow>(sql::BY_LEVEL)
            .bind(level.as_str())
            .bind(safe_limit(limit))
            .fetch_all(pool)
            .await
            .map_err(|e| AuraError::database(format!("get_by_level: {e}")))?;
        Ok(rows.into_iter().map(AlertRow::into_stored).collect())
    }

    /// Get alerts filtered by category.
    pub async fn get_by_category(
        pool: &PgPool,
        category: AlertCategory,
        limit: i64,
    ) -> AuraResult<Vec<StoredAlert>> {
        let rows = sqlx::query_as::<_, AlertRow>(sql::BY_CATEGORY)
            .bind(category.as_str())
            .bind(safe_limit(limit))
            .fetch_all(pool)
            .await
            .map_err(|e| AuraError::database(format!("get_by_category: {e}")))?;
        Ok(rows.into_iter().map(AlertRow::into_stored).collect())
    }

    /// Get alerts for a specific PV.
    pub async fn get_by_pv(
        pool: &PgPool,
        pv_name: &str,
        limit: i64,
    ) -> AuraResult<Vec<StoredAlert>> {
        let rows = sqlx::query_as::<_, AlertRow>(sql::BY_PV)
            .bind(pv_name)
            .bind(safe_limit(limit))
            .fetch_all(pool)
            .await
            .map_err(|e| AuraError::database(format!("get_by_pv: {e}")))?;
        Ok(rows.into_iter().map(AlertRow::into_stored).collect())
    }

    /// Acknowledge a single alert. Returns true if updated.
    pub async fn acknowledge(pool: &PgPool, alert_id: i64, by: &str) -> AuraResult<bool> {
        let result = sqlx::query(sql::ACKNOWLEDGE)
            .bind(by)
            .bind(alert_id)
            .execute(pool)
            .await
            .map_err(|e| AuraError::database(format!("acknowledge: {e}")))?;
        Ok(result.rows_affected() > 0)
    }

    /// Acknowledge multiple alerts in one round-trip.
    pub async fn acknowledge_batch(pool: &PgPool, alert_ids: &[i64], by: &str) -> AuraResult<u64> {
        if alert_ids.is_empty() {
            return Ok(0);
        }
        let result = sqlx::query(sql::ACKNOWLEDGE_BATCH)
            .bind(by)
            .bind(alert_ids)
            .execute(pool)
            .await
            .map_err(|e| AuraError::database(format!("acknowledge_batch: {e}")))?;
        Ok(result.rows_affected())
    }

    /// Count total unacknowledged alerts.
    pub async fn count_unacked(pool: &PgPool) -> AuraResult<i64> {
        let count: Option<i64> = sqlx::query_scalar(sql::COUNT_UNACKED)
            .fetch_one(pool)
            .await
            .map_err(|e| AuraError::database(format!("count_unacked: {e}")))?;
        Ok(count.unwrap_or(0))
    }

    /// Get unacknowledged alert counts grouped by level.
    pub async fn summary(pool: &PgPool) -> AuraResult<AlertSummary> {
        let rows: Vec<(String, i64)> = sqlx::query_as(sql::COUNT_BY_LEVEL)
            .fetch_all(pool)
            .await
            .map_err(|e| AuraError::database(format!("summary: {e}")))?;

        let mut summary = AlertSummary::default();
        for (level, count) in rows {
            match level.as_str() {
                "info" => summary.info = count,
                "warning" => summary.warning = count,
                "critical" => summary.critical = count,
                _ => tracing::warn!(level = %level, "unknown level in summary"),
            }
        }
        Ok(summary)
    }

    /// Delete alerts older than cutoff. Returns number deleted.
    pub async fn purge_before(pool: &PgPool, cutoff: DateTime<Utc>) -> AuraResult<u64> {
        let result = sqlx::query(sql::DELETE_OLD)
            .bind(cutoff)
            .execute(pool)
            .await
            .map_err(|e| AuraError::database(format!("purge_before: {e}")))?;
        Ok(result.rows_affected())
    }
}

impl fmt::Debug for AlertDao {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("AlertDao").finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_level_as_str() {
        assert_eq!(AlertLevel::Info.as_str(), "info");
        assert_eq!(AlertLevel::Warning.as_str(), "warning");
        assert_eq!(AlertLevel::Critical.as_str(), "critical");
    }

    #[test]
    fn test_level_from_str_valid() {
        assert_eq!("info".parse::<AlertLevel>().unwrap(), AlertLevel::Info);
        assert_eq!(
            "warning".parse::<AlertLevel>().unwrap(),
            AlertLevel::Warning
        );
        assert_eq!(
            "critical".parse::<AlertLevel>().unwrap(),
            AlertLevel::Critical
        );
    }

    #[test]
    fn test_level_from_str_invalid() {
        let err = "garbage".parse::<AlertLevel>().unwrap_err();
        assert!(err.contains("unknown alert level"));
        assert!(err.contains("garbage"));
    }

    #[test]
    fn test_level_from_str_empty() {
        assert!("".parse::<AlertLevel>().is_err());
    }

    #[test]
    fn test_level_from_str_case_sensitive() {
        assert!("INFO".parse::<AlertLevel>().is_err());
        assert!("Warning".parse::<AlertLevel>().is_err());
    }

    #[test]
    fn test_level_severity_ordering() {
        assert!(AlertLevel::Info.severity() < AlertLevel::Warning.severity());
        assert!(AlertLevel::Warning.severity() < AlertLevel::Critical.severity());
    }

    #[test]
    fn test_level_ord() {
        let mut levels = vec![AlertLevel::Critical, AlertLevel::Info, AlertLevel::Warning];
        levels.sort();
        assert_eq!(
            levels,
            vec![AlertLevel::Info, AlertLevel::Warning, AlertLevel::Critical]
        );
    }

    #[test]
    fn test_level_all_roundtrip() {
        for level in AlertLevel::ALL {
            assert_eq!(level.as_str().parse::<AlertLevel>().unwrap(), level);
        }
    }

    #[test]
    fn test_level_display() {
        assert_eq!(AlertLevel::Critical.to_string(), "critical");
    }

    #[test]
    fn test_level_copy() {
        let a = AlertLevel::Warning;
        let b = a;
        assert_eq!(a, b);
    }

    #[test]
    fn test_level_hash() {
        use std::collections::HashSet;
        let set: HashSet<AlertLevel> = AlertLevel::ALL.iter().copied().collect();
        assert_eq!(set.len(), 3);
    }

    #[test]
    fn test_category_as_str() {
        assert_eq!(AlertCategory::System.as_str(), "system");
        assert_eq!(AlertCategory::Pv.as_str(), "pv");
        assert_eq!(AlertCategory::Ioc.as_str(), "ioc");
        assert_eq!(AlertCategory::Shard.as_str(), "shard");
    }

    #[test]
    fn test_category_from_str_valid() {
        for cat in AlertCategory::ALL {
            assert_eq!(cat.as_str().parse::<AlertCategory>().unwrap(), cat);
        }
    }

    #[test]
    fn test_category_from_str_invalid() {
        let err = "nonsense".parse::<AlertCategory>().unwrap_err();
        assert!(err.contains("unknown alert category"));
    }

    #[test]
    fn test_category_display() {
        assert_eq!(AlertCategory::Ioc.to_string(), "ioc");
    }

    #[test]
    fn test_category_hash() {
        use std::collections::HashSet;
        let set: HashSet<AlertCategory> = AlertCategory::ALL.iter().copied().collect();
        assert_eq!(set.len(), 4);
    }

    #[test]
    fn test_alert_new_defaults() {
        let a = Alert::new(AlertLevel::Warning, AlertCategory::Pv, "PV not connected");
        assert_eq!(a.level, AlertLevel::Warning);
        assert_eq!(a.category, AlertCategory::Pv);
        assert_eq!(a.message, "PV not connected");
        assert_eq!(a.source.as_ref(), "store"); // static borrow
        assert!(a.pv_name.is_none());
        assert!(a.ioc_guid.is_none());
        assert!(a.details.is_object());
    }

    #[test]
    fn test_alert_source_static_no_alloc() {
        let a = Alert::new(AlertLevel::Info, AlertCategory::System, "test")
            .with_source_static(sources::DISCOVER);
        assert_eq!(a.source.as_ref(), "discover");
        assert!(matches!(a.source, Cow::Borrowed(_)));
    }

    #[test]
    fn test_alert_source_dynamic_alloc() {
        let a = Alert::new(AlertLevel::Info, AlertCategory::System, "test")
            .with_source("custom-source");
        assert_eq!(a.source.as_ref(), "custom-source");
        assert!(matches!(a.source, Cow::Owned(_)));
    }

    #[test]
    fn test_alert_pv_static() {
        let a = Alert::new(AlertLevel::Info, AlertCategory::Pv, "test")
            .with_pv_static("PERLE:Gun:Vacuum");
        assert!(matches!(a.pv_name, Some(Cow::Borrowed("PERLE:Gun:Vacuum"))));
    }

    #[test]
    fn test_alert_builders() {
        let a = Alert::new(AlertLevel::Critical, AlertCategory::Ioc, "IOC offline")
            .with_source_static(sources::DISCOVER)
            .with_pv("CRYO:TEMP")
            .with_ioc("guid-abc")
            .with_details(json!({"last_seen": "2026-01-01"}));

        assert_eq!(a.source.as_ref(), "discover");
        assert_eq!(a.pv_name.as_deref(), Some("CRYO:TEMP"));
        assert_eq!(a.ioc_guid.as_deref(), Some("guid-abc"));
        assert_eq!(a.details["last_seen"], "2026-01-01");
    }

    #[test]
    fn test_alert_display() {
        let a = Alert::new(AlertLevel::Critical, AlertCategory::Ioc, "IOC down");
        assert_eq!(a.to_string(), "[critical] ioc: IOC down");
    }

    #[test]
    fn test_alert_clone() {
        let a = Alert::new(AlertLevel::Warning, AlertCategory::Pv, "test")
            .with_pv("PV:A")
            .with_details(json!({"x": 1}));
        let b = a.clone();
        assert_eq!(a.message, b.message);
        assert_eq!(a.pv_name.as_deref(), b.pv_name.as_deref());
    }

    #[test]
    fn test_alert_mem_size_static_smaller() {
        let static_alert = Alert::new(AlertLevel::Info, AlertCategory::System, "ok")
            .with_source_static(sources::STORE);
        let dynamic_alert = Alert::new(AlertLevel::Info, AlertCategory::System, "ok")
            .with_source("some-dynamic-source-name");
        // Static source contributes 0 heap bytes, dynamic contributes len.
        assert!(static_alert.mem_size() < dynamic_alert.mem_size());
    }

    #[test]
    fn test_alert_mem_size_scales() {
        let small = Alert::new(AlertLevel::Info, AlertCategory::System, "ok");
        let large = Alert::new(AlertLevel::Critical, AlertCategory::Pv, "x".repeat(1000))
            .with_pv("VERY:LONG:PV:NAME")
            .with_ioc("guid-12345678")
            .with_details(json!({"data": [1,2,3,4,5]}));
        assert!(large.mem_size() > small.mem_size());
    }

    fn make_stored(level: AlertLevel, acked: bool) -> StoredAlert {
        StoredAlert {
            id: 1,
            time: Utc::now(),
            level,
            source: "test".to_string(),
            category: AlertCategory::System,
            pv_name: None,
            ioc_guid: None,
            message: "test".to_string(),
            details: json!({}),
            acknowledged: acked,
        }
    }

    #[test]
    fn test_stored_is_critical() {
        assert!(make_stored(AlertLevel::Critical, false).is_critical());
        assert!(!make_stored(AlertLevel::Warning, false).is_critical());
    }

    #[test]
    fn test_stored_age() {
        let a = make_stored(AlertLevel::Info, false);
        assert!(a.age().num_milliseconds() >= 0);
    }

    #[test]
    fn test_stored_display_unacked() {
        let s = StoredAlert {
            id: 42,
            time: Utc::now(),
            level: AlertLevel::Warning,
            source: "discover".to_string(),
            category: AlertCategory::Ioc,
            pv_name: None,
            ioc_guid: None,
            message: "IOC lost".to_string(),
            details: json!({}),
            acknowledged: false,
        }
        .to_string();
        assert!(s.contains("#42"));
        assert!(s.contains("[warning]"));
        assert!(!s.contains("(ack)"));
    }

    #[test]
    fn test_stored_display_acked() {
        assert!(
            make_stored(AlertLevel::Info, true)
                .to_string()
                .contains("(ack)")
        );
    }

    #[test]
    fn test_summary_default_clear() {
        let s = AlertSummary::default();
        assert!(s.is_clear());
        assert!(!s.has_critical());
    }

    #[test]
    fn test_summary_counts() {
        let s = AlertSummary {
            info: 5,
            warning: 3,
            critical: 1,
        };
        assert_eq!(s.total(), 9);
        assert!(s.has_critical());
        assert!(!s.is_clear());
    }

    #[test]
    fn test_summary_display() {
        let s = AlertSummary {
            info: 5,
            warning: 3,
            critical: 1,
        }
        .to_string();
        assert!(s.contains("9 alerts"));
        assert!(s.contains("1 critical"));
    }

    #[test]
    fn test_summary_eq() {
        assert_eq!(
            AlertSummary {
                info: 1,
                warning: 2,
                critical: 3
            },
            AlertSummary {
                info: 1,
                warning: 2,
                critical: 3
            },
        );
    }

    #[test]
    fn test_row_into_stored_valid() {
        let row = AlertRow {
            id: 42,
            time: Utc::now(),
            level: "critical".to_string(),
            source: "discover".to_string(),
            category: "ioc".to_string(),
            pv_name: Some("PV:A".to_string()),
            ioc_guid: Some("guid-x".to_string()),
            message: "IOC offline".to_string(),
            details: json!({"k": 1}),
            acknowledged: true,
        };
        let s = row.into_stored();
        assert_eq!(s.level, AlertLevel::Critical);
        assert_eq!(s.category, AlertCategory::Ioc);
        assert_eq!(s.source, "discover"); // moved, not cloned
        assert!(s.acknowledged);
    }

    #[test]
    fn test_row_unknown_level_defaults_warning() {
        let row = AlertRow {
            id: 1,
            time: Utc::now(),
            level: "garbage".to_string(),
            source: "x".to_string(),
            category: "system".to_string(),
            pv_name: None,
            ioc_guid: None,
            message: "test".to_string(),
            details: json!({}),
            acknowledged: false,
        };
        // This would log a tracing::warn in production.
        let s = row.into_stored();
        assert_eq!(s.level, AlertLevel::Warning);
    }

    #[test]
    fn test_row_unknown_category_defaults_system() {
        let row = AlertRow {
            id: 1,
            time: Utc::now(),
            level: "info".to_string(),
            source: "x".to_string(),
            category: "nonsense".to_string(),
            pv_name: None,
            ioc_guid: None,
            message: "test".to_string(),
            details: json!({}),
            acknowledged: false,
        };
        let s = row.into_stored();
        assert_eq!(s.category, AlertCategory::System);
    }

    #[test]
    fn test_sql_insert() {
        assert!(sql::INSERT.contains("alert_log"));
        assert!(sql::INSERT.contains("RETURNING id"));
    }

    #[test]
    fn test_sql_insert_unnest() {
        assert!(sql::INSERT_UNNEST.contains("UNNEST"));
        assert!(sql::INSERT_UNNEST.contains("RETURNING id"));
        assert!(sql::INSERT_UNNEST.contains("jsonb[]"));
    }

    #[test]
    fn test_sql_queries() {
        assert!(sql::RECENT.contains("ORDER BY time DESC"));
        assert!(sql::UNACKED.contains("acknowledged = FALSE"));
        assert!(sql::BY_TIME_RANGE.contains("time >= $1"));
        assert!(sql::BY_LEVEL.contains("level = $1"));
        assert!(sql::BY_CATEGORY.contains("category = $1"));
        assert!(sql::BY_PV.contains("pv_name = $1"));
        assert!(sql::ACKNOWLEDGE.contains("acknowledged = TRUE"));
        assert!(sql::ACKNOWLEDGE_BATCH.contains("ANY($2)"));
        assert!(sql::COUNT_BY_LEVEL.contains("GROUP BY level"));
        assert!(sql::DELETE_OLD.contains("DELETE"));
    }

    #[test]
    fn test_safe_limit() {
        assert_eq!(safe_limit(0), 1);
        assert_eq!(safe_limit(-5), 1);
        assert_eq!(safe_limit(100), 100);
        assert_eq!(safe_limit(50_000), 10_000);
        assert_eq!(safe_limit(10_000), 10_000);
    }

    #[test]
    fn test_sources_are_static() {
        assert_eq!(sources::STORE, "store");
        assert_eq!(sources::DISCOVER, "discover");
        assert_eq!(sources::INGEST, "ingest");
        assert_eq!(sources::API, "api");
        assert_eq!(sources::SYSTEM, "system");
    }

    #[test]
    fn test_dao_debug() {
        assert!(format!("{:?}", AlertDao).contains("AlertDao"));
    }
}
