//! Reconciler - diff desired state (pv_config) vs actual state (network).
//!
//! Pure logic, no I/O. Takes the current known state and produces
//! a list of actions for the orchestrator to execute.

use std::collections::HashSet;
use std::net::SocketAddr;

use crate::config_poller::PvChange;
use aura_core::AlertLevel;

/// An action the orchestrator must execute.
#[derive(Debug, Clone, PartialEq)]
pub enum Action {
    /// Search + introspect these PVs (new or re-enabled).
    Resolve(Vec<String>),
    /// Send subscribe commands to ingest for these PVs.
    Subscribe(Vec<(String, Option<SocketAddr>)>),
    /// Send unsubscribe commands for these PVs.
    Unsubscribe(Vec<String>),
    /// Update filter params in pv_config for these PVs.
    UpdateFilter(Vec<String>),
    /// Generate an alert.
    Alert(Alert),
}

/// An alert generated by the reconciler.
#[derive(Debug, Clone, PartialEq)]
pub struct Alert {
    pub level: AlertLevel,
    pub message: String,
    pub pv_name: Option<String>,
}

impl std::fmt::Display for Alert {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let prefix = match self.level {
            AlertLevel::Info => "INFO",
            AlertLevel::Warning => "WARN",
            AlertLevel::Critical => "CRIT",
        };
        match &self.pv_name {
            Some(pv) => write!(f, "[{prefix}] {pv}: {}", self.message),
            None => write!(f, "[{prefix}] {}", self.message),
        }
    }
}

/// Tracks which PVs are resolved (search done) and which are pending.
pub struct Reconciler {
    /// PVs that have been resolved (search + introspect done).
    resolved: HashSet<String>,
    /// PVs waiting for resolution (search in progress or not started).
    pending: HashSet<String>,
    /// PVs that failed resolution (not found on network).
    not_found: HashSet<String>,
    /// Stats.
    pub total_reconciliations: u64,
    pub total_actions: u64,
}

impl Reconciler {
    pub fn new() -> Self {
        Self {
            resolved: HashSet::new(),
            pending: HashSet::new(),
            not_found: HashSet::new(),
            total_reconciliations: 0,
            total_actions: 0,
        }
    }

    /// Process config changes and produce actions.
    ///
    /// This is the core logic: changes in -> actions out.
    pub fn reconcile(&mut self, changes: &[PvChange]) -> Vec<Action> {
        self.total_reconciliations += 1;
        if changes.is_empty() {
            return Vec::new();
        }

        let mut to_resolve = Vec::new();
        let mut to_unsubscribe = Vec::new();
        let mut to_update_filter = Vec::new();
        let mut actions = Vec::new();

        for change in changes {
            match change {
                PvChange::Added(cfg) => {
                    self.pending.insert(cfg.pv_name.clone());
                    to_resolve.push(cfg.pv_name.clone());
                }
                PvChange::Removed(name) => {
                    self.resolved.remove(name.as_str());
                    self.pending.remove(name.as_str());
                    self.not_found.remove(name.as_str());
                    to_unsubscribe.push(name.clone());
                }
                PvChange::Modified(cfg) => {
                    if self.resolved.contains(&cfg.pv_name) {
                        to_update_filter.push(cfg.pv_name.clone());
                    } else {
                        // Not yet resolved — re-add to pending.
                        self.pending.insert(cfg.pv_name.clone());
                        to_resolve.push(cfg.pv_name.clone());
                    }
                }
            }
        }

        if !to_resolve.is_empty() {
            actions.push(Action::Resolve(to_resolve));
        }
        if !to_unsubscribe.is_empty() {
            actions.push(Action::Unsubscribe(to_unsubscribe));
        }
        if !to_update_filter.is_empty() {
            actions.push(Action::UpdateFilter(to_update_filter));
        }

        self.total_actions += actions.len() as u64;
        actions
    }

    /// Mark PVs as successfully resolved (search + introspect done).
    /// Returns the list of PVs to subscribe.
    pub fn mark_resolved(
        &mut self,
        pv_names: &[String],
        ioc_addr: SocketAddr,
    ) -> Vec<(String, Option<SocketAddr>)> {
        let mut to_subscribe = Vec::with_capacity(pv_names.len());
        for name in pv_names {
            self.pending.remove(name.as_str());
            self.not_found.remove(name.as_str());
            // Only clone once — into resolved. Reuse the same String for to_subscribe.
            if self.resolved.insert(name.clone()) {
                // insert() returns true if the value was newly inserted.
                // Only subscribe if not already resolved (avoids duplicate subscribes).
                to_subscribe.push((name.clone(), Some(ioc_addr)));
            }
        }
        to_subscribe
    }

    /// Mark PVs as not found on the network.
    pub fn mark_not_found(&mut self, pv_names: &[String]) -> Vec<Action> {
        let mut actions = Vec::new();
        for name in pv_names {
            self.pending.remove(name.as_str());
            if self.not_found.insert(name.clone()) {
                // First time not found — generate alert.
                actions.push(Action::Alert(Alert {
                    level: AlertLevel::Warning,
                    message: "PV not found on EPICS network".into(),
                    pv_name: Some(name.clone()),
                }));
            }
        }
        actions
    }

    /// Mark a PV as disconnected (IOC lost).
    pub fn mark_disconnected(&mut self, pv_name: &str) -> Option<Action> {
        if self.resolved.remove(pv_name) {
            self.pending.insert(pv_name.to_string());
            Some(Action::Alert(Alert {
                level: AlertLevel::Warning,
                message: "IOC disconnected — PV will be re-resolved".into(),
                pv_name: Some(pv_name.to_string()),
            }))
        } else {
            None
        }
    }

    pub fn resolved_count(&self) -> usize {
        self.resolved.len()
    }

    pub fn pending_count(&self) -> usize {
        self.pending.len()
    }

    pub fn not_found_count(&self) -> usize {
        self.not_found.len()
    }

    pub fn is_resolved(&self, pv_name: &str) -> bool {
        self.resolved.contains(pv_name)
    }

    pub fn is_pending(&self, pv_name: &str) -> bool {
        self.pending.contains(pv_name)
    }

    pub fn is_not_found(&self, pv_name: &str) -> bool {
        self.not_found.contains(pv_name)
    }

    pub fn pending_names(&self) -> Vec<&str> {
        self.pending.iter().map(|s| s.as_str()).collect()
    }
}

impl Default for Reconciler {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for Reconciler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "Reconciler[{} resolved, {} pending, {} not_found]",
            self.resolved.len(),
            self.pending.len(),
            self.not_found.len()
        )
    }
}

impl std::fmt::Debug for Reconciler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Reconciler")
            .field("resolved", &self.resolved.len())
            .field("pending", &self.pending.len())
            .field("not_found", &self.not_found.len())
            .field("reconciliations", &self.total_reconciliations)
            .field("actions", &self.total_actions)
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use aura_core::pv::PvConfig;

    fn pv(name: &str) -> PvConfig {
        PvConfig::new(name)
    }
    fn addr(n: u8) -> SocketAddr {
        SocketAddr::new(std::net::Ipv4Addr::new(10, 0, 1, n).into(), 5075)
    }

    fn count_type(actions: &[Action], f: impl Fn(&Action) -> bool) -> usize {
        actions.iter().filter(|a| f(a)).count()
    }

    #[test]
    fn test_new() {
        let r = Reconciler::new();
        assert_eq!(r.resolved_count(), 0);
        assert_eq!(r.pending_count(), 0);
        assert_eq!(r.not_found_count(), 0);
    }
    #[test]
    fn test_default() {
        assert_eq!(Reconciler::default().resolved_count(), 0);
    }

    #[test]
    fn test_reconcile_empty() {
        let mut r = Reconciler::new();
        assert!(r.reconcile(&[]).is_empty());
        assert_eq!(r.total_reconciliations, 1);
    }

    #[test]
    fn test_reconcile_add() {
        let mut r = Reconciler::new();
        let actions = r.reconcile(&[PvChange::Added(pv("A")), PvChange::Added(pv("B"))]);
        assert_eq!(count_type(&actions, |a| matches!(a, Action::Resolve(_))), 1);
        if let Action::Resolve(names) = &actions[0] {
            assert_eq!(names.len(), 2);
        }
        assert!(r.is_pending("A"));
        assert!(r.is_pending("B"));
    }

    #[test]
    fn test_reconcile_remove() {
        let mut r = Reconciler::new();
        r.reconcile(&[PvChange::Added(pv("A"))]);
        r.mark_resolved(&["A".into()], addr(1));
        let actions = r.reconcile(&[PvChange::Removed("A".into())]);
        assert_eq!(
            count_type(&actions, |a| matches!(a, Action::Unsubscribe(_))),
            1
        );
        assert!(!r.is_resolved("A"));
    }

    #[test]
    fn test_reconcile_remove_pending() {
        let mut r = Reconciler::new();
        r.reconcile(&[PvChange::Added(pv("A"))]);
        assert!(r.is_pending("A"));
        r.reconcile(&[PvChange::Removed("A".into())]);
        assert!(!r.is_pending("A"));
    }

    #[test]
    fn test_reconcile_modify_resolved() {
        let mut r = Reconciler::new();
        r.reconcile(&[PvChange::Added(pv("A"))]);
        r.mark_resolved(&["A".into()], addr(1));
        let actions = r.reconcile(&[PvChange::Modified(pv("A"))]);
        assert_eq!(
            count_type(&actions, |a| matches!(a, Action::UpdateFilter(_))),
            1
        );
    }

    #[test]
    fn test_reconcile_modify_pending() {
        let mut r = Reconciler::new();
        r.reconcile(&[PvChange::Added(pv("A"))]);
        // A is still pending (not resolved yet) — re-resolve.
        let actions = r.reconcile(&[PvChange::Modified(pv("A"))]);
        assert_eq!(count_type(&actions, |a| matches!(a, Action::Resolve(_))), 1);
    }

    #[test]
    fn test_mark_resolved() {
        let mut r = Reconciler::new();
        r.reconcile(&[PvChange::Added(pv("A"))]);
        let subs = r.mark_resolved(&["A".into()], addr(1));
        assert_eq!(subs.len(), 1);
        assert_eq!(subs[0].0, "A");
        assert!(r.is_resolved("A"));
        assert!(!r.is_pending("A"));
    }

    #[test]
    fn test_mark_resolved_clears_not_found() {
        let mut r = Reconciler::new();
        r.reconcile(&[PvChange::Added(pv("A"))]);
        r.mark_not_found(&["A".into()]);
        assert!(r.is_not_found("A"));
        r.mark_resolved(&["A".into()], addr(1));
        assert!(!r.is_not_found("A"));
    }

    #[test]
    fn test_mark_not_found() {
        let mut r = Reconciler::new();
        r.reconcile(&[PvChange::Added(pv("A"))]);
        let alerts = r.mark_not_found(&["A".into()]);
        assert_eq!(alerts.len(), 1);
        assert!(r.is_not_found("A"));
        assert!(!r.is_pending("A"));
    }

    #[test]
    fn test_mark_not_found_no_duplicate_alert() {
        let mut r = Reconciler::new();
        r.reconcile(&[PvChange::Added(pv("A"))]);
        r.mark_not_found(&["A".into()]);
        let alerts = r.mark_not_found(&["A".into()]); // second time
        assert!(alerts.is_empty()); // no duplicate alert
    }

    #[test]
    fn test_mark_disconnected() {
        let mut r = Reconciler::new();
        r.reconcile(&[PvChange::Added(pv("A"))]);
        r.mark_resolved(&["A".into()], addr(1));
        let alert = r.mark_disconnected("A");
        assert!(alert.is_some());
        assert!(r.is_pending("A"));
        assert!(!r.is_resolved("A"));
    }

    #[test]
    fn test_mark_disconnected_unknown() {
        assert!(Reconciler::new().mark_disconnected("X").is_none());
    }

    #[test]
    fn test_full_lifecycle() {
        let mut r = Reconciler::new();

        // 1. Add 3 PVs.
        r.reconcile(&[
            PvChange::Added(pv("A")),
            PvChange::Added(pv("B")),
            PvChange::Added(pv("C")),
        ]);
        assert_eq!(r.pending_count(), 3);

        // 2. Resolve A and B.
        r.mark_resolved(&["A".into(), "B".into()], addr(1));
        assert_eq!(r.resolved_count(), 2);
        assert_eq!(r.pending_count(), 1);

        // 3. C not found.
        r.mark_not_found(&["C".into()]);
        assert_eq!(r.not_found_count(), 1);

        // 4. B's IOC disconnects.
        r.mark_disconnected("B");
        assert_eq!(r.resolved_count(), 1);
        assert_eq!(r.pending_count(), 1); // B pending

        // 5. Remove A.
        r.reconcile(&[PvChange::Removed("A".into())]);
        assert_eq!(r.resolved_count(), 0);

        // 6. C found on retry.
        r.mark_resolved(&["C".into()], addr(2));
        assert_eq!(r.resolved_count(), 1);
        assert_eq!(r.not_found_count(), 0);
    }

    #[test]
    fn test_stats() {
        let mut r = Reconciler::new();
        r.reconcile(&[PvChange::Added(pv("A"))]);
        r.reconcile(&[]);
        assert_eq!(r.total_reconciliations, 2);
        assert_eq!(r.total_actions, 1);
    }

    #[test]
    fn test_alert_display() {
        let a = Alert {
            level: AlertLevel::Warning,
            message: "test".into(),
            pv_name: Some("PV:A".into()),
        };
        assert_eq!(a.to_string(), "[WARN] PV:A: test");
    }
    #[test]
    fn test_alert_display_no_pv() {
        let a = Alert {
            level: AlertLevel::Critical,
            message: "system".into(),
            pv_name: None,
        };
        assert_eq!(a.to_string(), "[CRIT] system");
    }

    #[test]
    fn test_display() {
        assert!(Reconciler::new().to_string().contains("Reconciler"));
    }
    #[test]
    fn test_debug() {
        assert!(format!("{:?}", Reconciler::new()).contains("Reconciler"));
    }

    #[test]
    fn test_reconcile_100k_adds() {
        let mut r = Reconciler::new();
        let changes: Vec<PvChange> = (0..100_000)
            .map(|i| PvChange::Added(pv(&format!("PV:{i}"))))
            .collect();
        let t = std::time::Instant::now();
        let actions = r.reconcile(&changes);
        let elapsed = t.elapsed();
        assert_eq!(r.pending_count(), 100_000);
        assert!(!actions.is_empty());
        assert!(
            elapsed.as_millis() < 500,
            "reconcile took {}ms",
            elapsed.as_millis()
        );
    }
}
